[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_swap_escrow = "6U2q3J5Ubi7gdboM1baGiz51kam7puCRo3QyztpEZ4FY"

[programs.devnet]
token_swap_escrow = "6U2q3J5Ubi7gdboM1baGiz51kam7puCRo3QyztpEZ4FY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/allen/token_swap_escrow/programs/token_swap_escrow/wallet/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
